version: '3.4'

services:
  nodenpmintro:
    image: nodenpmintro
    build:
      context: node-npm_intro
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
